export const DEFAULT_ITEMS = [
  // ==================== Clothing ====================
  {
    name: "T-shirts",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },
  {
    name: "Underwear",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },
  {
    name: "Socks",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },
  {
    name: "Pants/Jeans",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perNDays" as const, value: 2 },
  },
  {
    name: "Shorts",
    category: "Clothing",
    tripTypes: ["vacation", "camping", "cityBreak"],
    weatherConditions: { temperature: 75, direction: "above" as const },
    quantityRule: { type: "perNDays" as const, value: 2 },
  },
  {
    name: "Pajamas",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Light jacket",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 65, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Winter coat",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 40, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Rain jacket",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { rain: true },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Sweater/Hoodie",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 60, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Dress shirts",
    category: "Clothing",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },
  {
    name: "Suit",
    category: "Clothing",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Tie",
    category: "Clothing",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 2 },
  },
  {
    name: "Dress shoes",
    category: "Clothing",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Casual shoes/Sneakers",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Sandals/Flip-flops",
    category: "Clothing",
    tripTypes: ["vacation", "camping"],
    weatherConditions: { temperature: 70, direction: "above" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Hiking boots",
    category: "Clothing",
    tripTypes: ["camping"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Swimsuit",
    category: "Clothing",
    tripTypes: ["vacation"],
    weatherConditions: { temperature: 70, direction: "above" as const },
    quantityRule: { type: "fixed" as const, value: 2 },
  },
  {
    name: "Belt",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Thermal underwear",
    category: "Clothing",
    tripTypes: ["camping", "cityBreak"],
    weatherConditions: { temperature: 35, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 2 },
  },
  {
    name: "Warm hat/Beanie",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 40, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Gloves",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 40, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Scarf",
    category: "Clothing",
    tripTypes: ["all"],
    weatherConditions: { temperature: 45, direction: "below" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Snow boots",
    category: "Clothing",
    tripTypes: ["camping", "cityBreak"],
    weatherConditions: { snow: true },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Athletic wear",
    category: "Clothing",
    tripTypes: ["vacation", "camping", "cityBreak"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 2 },
  },

  // ==================== Toiletries ====================
  {
    name: "Toothbrush",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Toothpaste",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Deodorant",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Shampoo",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Conditioner",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Body wash/Soap",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Razor",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Sunscreen",
    category: "Toiletries",
    tripTypes: ["vacation", "camping", "cityBreak"],
    weatherConditions: { temperature: 65, direction: "above" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Lip balm",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Hairbrush/Comb",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Insect repellent",
    category: "Toiletries",
    tripTypes: ["camping", "vacation"],
    weatherConditions: { temperature: 60, direction: "above" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Hand sanitizer",
    category: "Toiletries",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },

  // ==================== Electronics ====================
  {
    name: "Phone charger",
    category: "Electronics",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Laptop",
    category: "Electronics",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Laptop charger",
    category: "Electronics",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Power bank",
    category: "Electronics",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Headphones/Earbuds",
    category: "Electronics",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Travel adapter",
    category: "Electronics",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Camera",
    category: "Electronics",
    tripTypes: ["vacation", "camping", "cityBreak"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "E-reader/Tablet",
    category: "Electronics",
    tripTypes: ["vacation", "business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Flashlight/Headlamp",
    category: "Electronics",
    tripTypes: ["camping"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },

  // ==================== Documents ====================
  {
    name: "Passport",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "ID/Driver's license",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Travel insurance docs",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Boarding pass/Tickets",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Hotel reservation",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Business cards",
    category: "Documents",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Credit cards/Cash",
    category: "Documents",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },

  // ==================== Accessories ====================
  {
    name: "Sunglasses",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Watch",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Umbrella",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: { rain: true },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Daypack/Backpack",
    category: "Accessories",
    tripTypes: ["vacation", "camping", "cityBreak"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Reusable water bottle",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Travel pillow",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Eye mask",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Packing cubes",
    category: "Accessories",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Sun hat",
    category: "Accessories",
    tripTypes: ["vacation", "camping"],
    weatherConditions: { temperature: 75, direction: "above" as const },
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Sleeping bag",
    category: "Accessories",
    tripTypes: ["camping"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Travel towel",
    category: "Accessories",
    tripTypes: ["camping", "vacation"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },

  // ==================== Health/Medicine ====================
  {
    name: "Prescription medications",
    category: "Health/Medicine",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },
  {
    name: "Pain relievers (Ibuprofen/Tylenol)",
    category: "Health/Medicine",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Band-aids/First aid kit",
    category: "Health/Medicine",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Allergy medicine",
    category: "Health/Medicine",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Vitamins",
    category: "Health/Medicine",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "perDay" as const, value: 1 },
  },

  // ==================== Miscellaneous ====================
  {
    name: "Snacks",
    category: "Miscellaneous",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Books/Magazines",
    category: "Miscellaneous",
    tripTypes: ["vacation", "business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Pen and notepad",
    category: "Miscellaneous",
    tripTypes: ["business", "cityBreak"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Ziplock bags",
    category: "Miscellaneous",
    tripTypes: ["all"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 3 },
  },
  {
    name: "Sewing kit",
    category: "Miscellaneous",
    tripTypes: ["business"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Multi-tool/Knife",
    category: "Miscellaneous",
    tripTypes: ["camping"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
  {
    name: "Deck of cards/Games",
    category: "Miscellaneous",
    tripTypes: ["vacation", "camping"],
    weatherConditions: null,
    quantityRule: { type: "fixed" as const, value: 1 },
  },
];
