CREATE TABLE "packing-list_category" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "packing-list_category_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "packing-list_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packing-list_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"user_id" text NOT NULL,
	"category_id" integer
);
--> statement-breakpoint
CREATE TABLE "packing-list_luggage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packing-list_luggage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"user_id" text NOT NULL,
	"capacity_days" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "packing-list_tag" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "packing-list_tag_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "packing-list_items_to_tags" (
	"item_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "packing-list_items_to_tags_item_id_tag_id_pk" PRIMARY KEY("item_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "packing-list_luggage_to_travel_mode_tags" (
	"luggage_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "packing-list_luggage_to_travel_mode_tags_luggage_id_tag_id_pk" PRIMARY KEY("luggage_id","tag_id")
);
--> statement-breakpoint
ALTER TABLE "packing-list_item" ADD CONSTRAINT "packing-list_item_category_id_packing-list_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."packing-list_category"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packing-list_items_to_tags" ADD CONSTRAINT "packing-list_items_to_tags_item_id_packing-list_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."packing-list_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packing-list_items_to_tags" ADD CONSTRAINT "packing-list_items_to_tags_tag_id_packing-list_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."packing-list_tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packing-list_luggage_to_travel_mode_tags" ADD CONSTRAINT "packing-list_luggage_to_travel_mode_tags_luggage_id_packing-list_luggage_id_fk" FOREIGN KEY ("luggage_id") REFERENCES "public"."packing-list_luggage"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "packing-list_luggage_to_travel_mode_tags" ADD CONSTRAINT "packing-list_luggage_to_travel_mode_tags_tag_id_packing-list_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."packing-list_tag"("id") ON DELETE cascade ON UPDATE no action;